name: toll_cam_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  rbush: ^1.1.1
  url_launcher: ^6.3.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/toll_segments.geojson
    - assets/data/toll_cameras_points.geojson